param(
  [string]$ProjectRef = "jvovcsuzahfwakcyltfe",
  [string]$SupabaseUrl = "",
  [string]$AnonKey = "",
  [string]$ServiceRoleKey = ""
)

$ErrorActionPreference = "Stop"

$defaultUrl = "https://$ProjectRef.supabase.co"

Write-Host "This will (re)write .env.local in the project root." -ForegroundColor Yellow
Write-Host "Get values from Supabase Dashboard -> Project Settings -> API." -ForegroundColor Yellow
Write-Host "Do NOT paste keys in chat. Paste only in this terminal prompt." -ForegroundColor Yellow

$url = $SupabaseUrl
if ([string]::IsNullOrWhiteSpace($url)) {
  $url = $env:SUPABASE_URL
}
if ([string]::IsNullOrWhiteSpace($url)) {
  $url = Read-Host "SUPABASE_URL [$defaultUrl]"
}
if ([string]::IsNullOrWhiteSpace($url)) { $url = $defaultUrl }

if ([string]::IsNullOrWhiteSpace($AnonKey)) {
  $AnonKey = $env:SUPABASE_ANON_KEY
}
if ([string]::IsNullOrWhiteSpace($ServiceRoleKey)) {
  $ServiceRoleKey = $env:SUPABASE_SERVICE_ROLE_KEY
}

if ([string]::IsNullOrWhiteSpace($AnonKey)) {
  $anonSecure = Read-Host "SUPABASE_ANON_KEY" -AsSecureString
}
if ([string]::IsNullOrWhiteSpace($ServiceRoleKey)) {
  $serviceSecure = Read-Host "SUPABASE_SERVICE_ROLE_KEY (optional; recommended for writes)" -AsSecureString
}

function SecureToPlain([Security.SecureString]$secure) {
  if ($null -eq $secure) { return "" }
  $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
  try {
    return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr)
  } finally {
    [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
  }
}

function Sanitize([string]$s) {
  if ([string]::IsNullOrWhiteSpace($s)) { return "" }
  # remove control chars
  $filtered = -join ($s.ToCharArray() | Where-Object { [int]$_ -ge 32 })
  return $filtered.Trim()
}

$anon = Sanitize($AnonKey)
$service = Sanitize($ServiceRoleKey)
if ($anonSecure) { $anon = Sanitize((SecureToPlain $anonSecure)) }
if ($serviceSecure) { $service = Sanitize((SecureToPlain $serviceSecure)) }

$url = Sanitize($url)

if ([string]::IsNullOrWhiteSpace($url)) { throw "SUPABASE_URL is required" }
if (-not ($url.StartsWith("https://") -or $url.StartsWith("http://"))) { throw "SUPABASE_URL must start with https://" }
if ([string]::IsNullOrWhiteSpace($anon) -and [string]::IsNullOrWhiteSpace($service)) {
  throw "Provide at least SUPABASE_ANON_KEY or SUPABASE_SERVICE_ROLE_KEY"
}

$lines = @(
  "# Auto-generated by scripts/setup_env.ps1",
  "SUPABASE_URL=$url",
  "SUPABASE_ANON_KEY=$anon",
  "SUPABASE_SERVICE_ROLE_KEY=$service"
)

Set-Content -Path ".env.local" -Value $lines -Encoding UTF8
Write-Host "OK: Wrote .env.local" -ForegroundColor Green
